Repository WinnerCat/backend, pull requests merged in 2024-07, with the labels that each got.

#2 Add/#1 project basecode choi76
  src/main/java/com/winner_cat/WinnercatApplication.java
  src/main/java/com/winner_cat/global/entity/BaseEntity.java
  src/main/java/com/winner_cat/global/enums/statuscode/BaseCode.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/winner_cat/global/enums/statuscode/SuccessStatus.java
  src/main/java/com/winner_cat/global/exception/ExceptionAdvice.java
  src/main/java/com/winner_cat/global/exception/GeneralException.java
  src/main/java/com/winner_cat/global/exception/controller/ResourceErrorController.java
  src/main/java/com/winner_cat/global/response/ApiResponse.java
Labels: :sparkles: Feat, :technologist: choi76, :white_check_mark: Add

#5 Feat/#3 security choi76
  build.gradle
  src/main/java/com/winner_cat/domain/member/controller/MemberController.java
  src/main/java/com/winner_cat/domain/member/controller/TestController.java
  src/main/java/com/winner_cat/domain/member/dto/JoinDTO.java
  src/main/java/com/winner_cat/domain/member/dto/LoginRequestDTO.java
  src/main/java/com/winner_cat/domain/member/entity/Member.java
  src/main/java/com/winner_cat/domain/member/repository/MemberRepository.java
  src/main/java/com/winner_cat/domain/member/service/MemberService.java
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/winner_cat/global/jwt/dto/CustomUserDetails.java
  src/main/java/com/winner_cat/global/jwt/filter/JWTFilter.java
  src/main/java/com/winner_cat/global/jwt/handler/CustomAccessDeniedHandler.java
  src/main/java/com/winner_cat/global/jwt/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/winner_cat/global/jwt/service/CustomUserDetailsService.java
  src/main/java/com/winner_cat/global/jwt/util/JwtUtil.java
Labels: :sparkles: Feat, :technologist: choi76

#7 Add/#6 design directory choi76
  .github/pull_request_template.md
  build.gradle
  src/main/java/com/winner_cat/WinnercatApplication.java
  src/main/java/com/winner_cat/domain/article/entity/Article.java
  src/main/java/com/winner_cat/domain/article/entity/Tag.java
  src/main/java/com/winner_cat/domain/member/controller/MemberController.java
  src/main/java/com/winner_cat/domain/member/controller/TestController.java
  src/main/java/com/winner_cat/domain/member/dto/JoinDTO.java
  src/main/java/com/winner_cat/domain/member/dto/LoginRequestDTO.java
  src/main/java/com/winner_cat/domain/member/entity/Member.java
  src/main/java/com/winner_cat/domain/member/repository/MemberRepository.java
  src/main/java/com/winner_cat/domain/member/service/MemberService.java
  src/main/java/com/winner_cat/domain/questionroom/entity/Answer.java
  src/main/java/com/winner_cat/domain/questionroom/entity/Question.java
  src/main/java/com/winner_cat/domain/questionroom/entity/QuestionRoom.java
  src/main/java/com/winner_cat/domain/questionroom/entity/enums/QuestionState.java
  src/main/java/com/winner_cat/domain/scrap/entity/Scrap.java
  src/main/java/com/winner_cat/domain/scream/entity/Scream.java
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
  src/main/java/com/winner_cat/global/entity/BaseEntity.java
  src/main/java/com/winner_cat/global/enums/statuscode/BaseCode.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/winner_cat/global/enums/statuscode/SuccessStatus.java
  src/main/java/com/winner_cat/global/exception/ExceptionAdvice.java
  src/main/java/com/winner_cat/global/exception/GeneralException.java
  src/main/java/com/winner_cat/global/exception/controller/ResourceErrorController.java
  src/main/java/com/winner_cat/global/jwt/dto/CustomUserDetails.java
  src/main/java/com/winner_cat/global/jwt/filter/JWTFilter.java
  src/main/java/com/winner_cat/global/jwt/handler/CustomAccessDeniedHandler.java
  src/main/java/com/winner_cat/global/jwt/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/winner_cat/global/jwt/service/CustomUserDetailsService.java
  src/main/java/com/winner_cat/global/jwt/util/JwtUtil.java
  src/main/java/com/winner_cat/global/response/ApiResponse.java
Labels: :technologist: choi76, :white_check_mark: Add

#9 Feat/#8 create article jungeun
  .idea/misc.xml
  .idea/modules/winnercat.main.iml
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/ArticleCreateDto.java
  src/main/java/com/winner_cat/domain/article/entity/Article.java
  src/main/java/com/winner_cat/domain/article/entity/ArticleTag.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleRepository.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleTagRepository.java
  src/main/java/com/winner_cat/domain/article/repository/TagRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#11 Feat/#10 modify article jungeun
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/ArticleUpdateDto.java
  src/main/java/com/winner_cat/domain/article/entity/Article.java
  src/main/java/com/winner_cat/domain/article/entity/ArticleTag.java
  src/main/java/com/winner_cat/domain/article/entity/Tag.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleTagRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#13 Feat/#12 delete article jungeun
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#14 Feat/#4 oauth2 google login choi76
  build.gradle
  src/main/java/com/winner_cat/domain/member/controller/MemberController.java
  src/main/java/com/winner_cat/domain/member/dto/JoinDTO.java
  src/main/java/com/winner_cat/domain/member/entity/Member.java
  src/main/java/com/winner_cat/domain/member/repository/MemberRepository.java
  src/main/java/com/winner_cat/domain/member/service/MemberService.java
  src/main/java/com/winner_cat/domain/oauth2/dto/CustomOAuth2User.java
  src/main/java/com/winner_cat/domain/oauth2/dto/GoogleResponse.java
  src/main/java/com/winner_cat/domain/oauth2/dto/OAuth2Response.java
  src/main/java/com/winner_cat/domain/oauth2/dto/UserDTO.java
  src/main/java/com/winner_cat/domain/oauth2/handler/CustomSuccessHandler.java
  src/main/java/com/winner_cat/domain/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
  src/main/java/com/winner_cat/global/jwt/dto/CustomUserDetails.java
  src/main/java/com/winner_cat/global/jwt/filter/JWTFilter.java
  src/main/java/com/winner_cat/global/jwt/handler/CustomAccessDeniedHandler.java
  src/main/java/com/winner_cat/global/jwt/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/winner_cat/global/jwt/util/JwtUtil.java
Labels: :rotating_light: Fix, :sparkles: Feat, :technologist: choi76

#17 Fix/#16 login api choi76
  .idea/misc.xml
  src/main/java/com/winner_cat/domain/member/controller/MemberController.java
  src/main/java/com/winner_cat/domain/member/service/MemberService.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
Labels: :rotating_light: Fix, :sparkles: Feat, :technologist: choi76

#19 Feat/#15 create scream jungeun
  .idea/modules/winnercat.main.iml
  src/main/java/com/winner_cat/domain/scream/controller/ScreamController.java
  src/main/java/com/winner_cat/domain/scream/dto/ScreamCreateDto.java
  src/main/java/com/winner_cat/domain/scream/repository/ScreamRepository.java
  src/main/java/com/winner_cat/domain/scream/service/ScreamService.java
  src/main/java/com/winner_cat/domain/scream/service/ScreamServiceImpl.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#23 Fix/#22 fix login jwt choi76
  src/main/java/com/winner_cat/domain/member/service/MemberService.java
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
  src/main/java/com/winner_cat/global/oauth2/handler/CustomSuccessHandler.java
  src/main/java/com/winner_cat/global/oauth2/service/CustomOAuth2UserService.java
Labels: :rotating_light: Fix, :technologist: choi76

#25 ✨ [feat] 오늘 작성한 아우성 전체 조회 기능 구현
  src/main/java/com/winner_cat/domain/scream/controller/ScreamController.java
  src/main/java/com/winner_cat/domain/scream/dto/ScreamCreateDto.java
  src/main/java/com/winner_cat/domain/scream/dto/ScreamListDto.java
  src/main/java/com/winner_cat/domain/scream/repository/ScreamRepository.java
  src/main/java/com/winner_cat/domain/scream/service/ScreamService.java
  src/main/java/com/winner_cat/domain/scream/service/ScreamServiceImpl.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#27 Feat/#26 check detail article jungeun
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/ArticleListDto.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleRepository.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleTagRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#28 Feat/#24 new question choi76
  src/main/java/com/winner_cat/domain/questionroom/controller/QuestionRoomController.java
  src/main/java/com/winner_cat/domain/questionroom/dto/NewQuestionResponseDTO.java
  src/main/java/com/winner_cat/domain/questionroom/entity/QuestionRoom.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionRoomService.java
Labels: :sparkles: Feat, :technologist: choi76

#31 Move/#29 move directory choi76
  src/main/java/com/winner_cat/domain/questionroom/controller/QuestionController.java
  src/main/java/com/winner_cat/domain/questionroom/controller/QuestionRoomController.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionRoomService.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionService.java
Labels: :technologist: choi76, :truck: Move

#37 Feat/#34 article scrap choi76
  src/main/java/com/winner_cat/domain/member/entity/Member.java
  src/main/java/com/winner_cat/domain/scrap/controller/ScrapController.java
  src/main/java/com/winner_cat/domain/scrap/entity/Scrap.java
  src/main/java/com/winner_cat/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/winner_cat/domain/scrap/service/ScrapService.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
  src/main/java/com/winner_cat/init/article/ArticleDataLoader.java
Labels: :sparkles: Feat, :technologist: choi76, :white_check_mark: Add

#39 Feat/#35 scrap preview choi76
  src/main/java/com/winner_cat/domain/scrap/controller/ScrapController.java
  src/main/java/com/winner_cat/domain/scrap/dto/ScrapPreviewResponseDTO.java
  src/main/java/com/winner_cat/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/winner_cat/domain/scrap/service/ScrapService.java
Labels: :sparkles: Feat, :technologist: choi76

#40 Feat/#38 check my article preview jungeun
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/ArticleListDto.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :sparkles: Feat, 👩🏻‍💻 jungeun

#41 Feat/#33 question room state choi76
  src/main/java/com/winner_cat/domain/questionroom/controller/QuestionRoomController.java
  src/main/java/com/winner_cat/domain/questionroom/dto/ChangeQuestionRoomStateDTO.java
  src/main/java/com/winner_cat/domain/questionroom/entity/QuestionRoom.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionRoomService.java
Labels: :sparkles: Feat, :technologist: choi76

#42 Feat/#32 check chatting choi76
  src/main/java/com/winner_cat/domain/questionroom/controller/QuestionRoomController.java
  src/main/java/com/winner_cat/domain/questionroom/dto/AnswerDto.java
  src/main/java/com/winner_cat/domain/questionroom/dto/CheckChattingRoomDetailDto.java
  src/main/java/com/winner_cat/domain/questionroom/dto/QuestionDto.java
  src/main/java/com/winner_cat/domain/questionroom/repository/AnswerRepository.java
  src/main/java/com/winner_cat/domain/questionroom/repository/QuestionRepository.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionRoomService.java
Labels: :sparkles: Feat, :technologist: choi76

#44 Feat/#43 check all article preivew choi76
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/AllArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76

#45 Feat/#36 search article by tag choi76
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/AllArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/dto/ArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleTagRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :recycle: Refactor, :sparkles: Feat, :technologist: choi76

#49 Ci/#48 ci pipeline choi76
  .github/workflows/gradle.yml
  .gitignore
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/md5-checksums.bin
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/dependencies-accessors/gc.properties
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileChanges/last-build.bin
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/8.8/gc.properties
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/cache.properties
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  .gradle/vcs-1/gc.properties
  .idea/misc.xml
  Dockerfile
  HELP.md
  build.gradle
  build/resolvedMainClassName
  build/tmp/bootJar/MANIFEST.MF
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig$1.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  gradle/wrapper/gradle-wrapper.jar
  src/main/java/com/winner_cat/domain/member/controller/TestController.java
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
Labels: :technologist: choi76, :construction_worker: CI

#56 Feat/#55 preview my article paging jungeun
  .gradle/8.8/checksums/checksums.lock
  .gradle/8.8/checksums/sha1-checksums.bin
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/buildOutputCleanup/outputFiles.bin
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig$1.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat, 👩🏻‍💻 jungeun

#58 Fix/#50 jwt setting choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/JWTFilter.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/PermitAllPathsConfig.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig$1.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/global/config/PermitAllPathsConfig.java
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
  src/main/java/com/winner_cat/global/jwt/filter/JWTFilter.java
Labels: :rotating_light: Fix, :sparkles: Feat, :technologist: choi76

#59 Feat/#53 tag color choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/JWTFilter.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/PermitAllPathsConfig.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapPreviewResponseDTO$ScrapPreviewResponseDTOBuilder.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapPreviewResponseDTO.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig$1.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/SecurityConfig.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/dto/ArticleCreateDto.java
  src/main/java/com/winner_cat/domain/article/dto/ArticleListDto.java
  src/main/java/com/winner_cat/domain/article/dto/ArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/dto/TagResponseDto.java
  src/main/java/com/winner_cat/domain/article/entity/Tag.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/domain/scrap/dto/ScrapPreviewResponseDTO.java
  src/main/java/com/winner_cat/domain/scrap/service/ScrapService.java
  src/main/java/com/winner_cat/init/article/ArticleDataLoader.java
Labels: :sparkles: Feat, :technologist: choi76

#60 Feat/#54 article preview total pages choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapPreviewResponseDTO$ScrapPreviewResponseDTOBuilder.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapPreviewResponseDTO.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId5
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/dto/ArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/domain/scrap/dto/ScrapDto.java
  src/main/java/com/winner_cat/domain/scrap/dto/ScrapPreviewResponseDTO.java
  src/main/java/com/winner_cat/domain/scrap/service/ScrapService.java
Labels: :sparkles: Feat, :technologist: choi76

#62 Feat/#57 article recomment choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/ArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :sparkles: Feat, :technologist: choi76

#63 Fix/#61 question room detail choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/AnswerDto$AnswerDtoBuilder.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/AnswerDto.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/CheckChattingRoomDetailDto$CheckChattingRoomDetailDtoBuilder.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/CheckChattingRoomDetailDto.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomService.class.uniqueId4
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/questionroom/dto/AnswerDto.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionRoomService.java
Labels: :rotating_light: Fix, :sparkles: Feat, :technologist: choi76

#65 ✅ [add] 이메일 조회 코드 추가 작성
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/dto/ArticlePreviewDto.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat, 👩🏻‍💻 jungeun

#67 🎨 [chore] 최근 게시글부터 조회하기
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/AnswerDto$AnswerDtoBuilder.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/AnswerDto.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleDataLoader.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleRepository.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/CheckChattingRoomDetailDto$CheckChattingRoomDetailDtoBuilder.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/CheckChattingRoomDetailDto.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomController.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomService.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId3
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/repository/ArticleRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat, 👩🏻‍💻 jungeun

#72 Feat/#71 scrap cancel choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId12
  build/tmp/compileJava/compileTransaction/stash-dir/CustomAccessDeniedHandler.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/CustomAuthenticationEntryPoint.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/CustomUserDetailsService.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ErrorStatus.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ExceptionAdvice.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/MemberService.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/PermitAllPathsConfig.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomService.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ResourceErrorController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapRepository.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId8
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/scrap/controller/ScrapController.java
  src/main/java/com/winner_cat/domain/scrap/repository/ScrapRepository.java
  src/main/java/com/winner_cat/domain/scrap/service/ScrapService.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, :technologist: choi76

#78 Fix/#77 preview article detail jungeun
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleDataLoader.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleListDto$ArticleResponse$ArticleResponseBuilder.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleListDto$ArticleResponse.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleListDto$SearchArticleRes$SearchArticleResBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleListDto$SearchArticleRes.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleListDto.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId12
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleTagRepository.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/CustomAccessDeniedHandler.class.uniqueId9
  build/tmp/compileJava/compileTransaction/stash-dir/CustomAuthenticationEntryPoint.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/CustomUserDetailsService.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ErrorStatus.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ExceptionAdvice.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/MemberService.class.uniqueId10
  build/tmp/compileJava/compileTransaction/stash-dir/PermitAllPathsConfig.class.uniqueId14
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomService.class.uniqueId13
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ResourceErrorController.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapRepository.class.uniqueId11
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId8
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat, 👩🏻‍💻 jungeun

#80 Fix/#79 delete article jungeun
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapRepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId3
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/domain/scrap/repository/ScrapRepository.java
Labels: :rotating_light: Fix, :sparkles: Feat, 👩🏻‍💻 jungeun

#82 Feat/#81 cors choi76
  src/main/java/com/winner_cat/global/config/SecurityConfig.java
  src/main/java/com/winner_cat/global/oauth2/handler/CustomSuccessHandler.java
  src/main/java/com/winner_cat/init/article/ArticleDataLoader.java
  src/main/java/com/winner_cat/init/questionroom/DataLoader.java
Labels: :rotating_light: Fix, :sparkles: Feat, :technologist: choi76

#83 Feat/#51 adopt answer choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapRepository.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/ScrapService.class.uniqueId3
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/questionroom/controller/QuestionRoomController.java
  src/main/java/com/winner_cat/domain/questionroom/dto/AdoptAnswerDto.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionRoomService.java
  src/main/java/com/winner_cat/domain/questionroom/service/QuestionService.java
  src/main/java/com/winner_cat/global/config/WebConfig.java
  src/main/java/com/winner_cat/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: Feat, :technologist: choi76
