Repository WinnerCat/backend, pull requests merged in 2024-08, with the labels that each got.

#85 Feat/#30 today error choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/DataLoader.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomController.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/QuestionRoomService.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/TagDataLoader.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/controller/ArticleController.java
  src/main/java/com/winner_cat/domain/article/dto/TodayErrorDto.java
  src/main/java/com/winner_cat/domain/article/entity/ArticleTag.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleRepository.java
  src/main/java/com/winner_cat/domain/article/repository/ArticleTagRepository.java
  src/main/java/com/winner_cat/domain/article/service/ArticleService.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/init/article/ArticleDataLoader.java
  src/main/java/com/winner_cat/init/questionroom/DataLoader.java
  src/main/java/com/winner_cat/init/tag/TagDataLoader.java
Labels: :sparkles: Feat, :technologist: choi76

#86 ✏️ [fix] 태그로 게시글 조회 미리보기 API 수정 - 모든 태그를 반환하도록
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleDataLoader.class.uniqueId0
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
Labels: :rotating_light: Fix, :technologist: choi76

#88 Fix/#87 today error choi76
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/buildOutputCleanup/buildOutputCleanup.lock
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl$ArticleServiceImplBuilder.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/ArticleServiceImpl.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/CustomSuccessHandler.class.uniqueId1
  build/tmp/compileJava/compileTransaction/stash-dir/PermitAllPathsConfig.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/WebConfig.class.uniqueId6
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/article/dto/TodayErrorDto.java
  src/main/java/com/winner_cat/domain/article/service/ArticleServiceImpl.java
  src/main/java/com/winner_cat/global/config/PermitAllPathsConfig.java
Labels: :rotating_light: Fix, :technologist: choi76

#92 fix/#90-scream-preview-jungeun
  .gradle/8.8/executionHistory/executionHistory.bin
  .gradle/8.8/executionHistory/executionHistory.lock
  .gradle/8.8/fileHashes/fileHashes.bin
  .gradle/8.8/fileHashes/fileHashes.lock
  .gradle/8.8/fileHashes/resourceHashesCache.bin
  .gradle/file-system.probe
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamListDto$ScreamResponse$ScreamResponseBuilder.class.uniqueId0
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamListDto$ScreamResponse.class.uniqueId3
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamListDto$SearchScreamsRes$SearchScreamsResBuilder.class.uniqueId6
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamListDto$SearchScreamsRes.class.uniqueId7
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamListDto.class.uniqueId5
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamRepository.class.uniqueId2
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamServiceImpl$ScreamServiceImplBuilder.class.uniqueId4
  build/tmp/compileJava/compileTransaction/stash-dir/ScreamServiceImpl.class.uniqueId1
  build/tmp/compileJava/previous-compilation-data.bin
  src/main/java/com/winner_cat/domain/scream/controller/ScreamController.java
  src/main/java/com/winner_cat/domain/scream/dto/ScreamListDto.java
  src/main/java/com/winner_cat/domain/scream/repository/ScreamRepository.java
  src/main/java/com/winner_cat/domain/scream/service/ScreamService.java
  src/main/java/com/winner_cat/domain/scream/service/ScreamServiceImpl.java
Labels: :rotating_light: Fix, :sparkles: Feat, 👩🏻‍💻 jungeun
